"""Durable Frosty research records (see docs/frosty/TOOLS.md "Frosty records").

schema                          print the record header (v1) that every receipt carries
check [--external] [--all]      validate receipts, records and generated files; exit 1 on errors only
check-receipt FILE              validate one draft receipt's `record` (read-only)
status                          short summary for orchestrators at run start
build                           regenerate asset-findings.json, lead-index.json, site-evidence.json
                                and the Closed leads table in docs/archive/FROSTY_QUEUE_CLOSED.md
ledger-drift [--out F]          data/sim files and data leaves that differ from the site-input ledger
new --kind decision --lead L67  write a skeleton decision record under reference-data/provenance/

Roots: --site-root (data/, sim/, ui/; pointers resolve here), --research-root (receipts, docs, queue),
--datamining-root (external evidence; default <research-root>/../BF6 Datamining). All default to the repo.
Receipts committed before the cutover carry their `record` in reference-data/provenance/records-legacy.json,
keyed by file name with the receipt's sha256 (CRLF read as LF, the form git stores); a committed receipt is never edited, only superseded.
"""
import argparse, collections, datetime, difflib, hashlib, json, re, runpy, sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SIDECAR = 'records-legacy.json'
NOTE = 'Generated by scripts/frosty-records.py build; do not edit.'
KINDS = ['lead', 'decision', 'audit', 'capture', 'mapping', 'reference']
STATUSES = ['finding', 'site-supported', 'site-fixed', 'proposal', 'needs-capture',
            'rejected', 'exhausted', 'parked', 'duplicate', 'superseded']
FORMATS = ['raw-ebx', 'xml', 'raw-res']
RESULTS = ['useful', 'unrelated-to-question', 'inconclusive', 'blocked-by-decoding']
RELATIONS = ['supports', 'contradicts', 'changed', 'proposed', 'context']
BINDINGS = ['site', 'research']
DESC_RELEASE = '91c9ea7c3dd830e34a78123c8bb7485e80eefdb18fc9c7ee41117971d23565c2'
DESC_HOTFIX = '99b49cfd8bdb5bb6f0181df8ac0d93a0396c1b7f07a1ba3ce8ca1cea45969640'
BUILDS = {  # build id -> Head and descriptor; the receipts' `build` shapes all resolve to one of these
    '1.4.3.0-release': {'head': '4892017', 'descriptorSha256': DESC_RELEASE, 'label': '1.4.3.0 release'},
    '1.4.3.0-hotfix': {'head': '4892087', 'descriptorSha256': DESC_HOTFIX, 'label': '1.4.3.1 hotfix (EA label)'},
    '1.4.2.5': {'head': None, 'descriptorSha256': None, 'label': '1.4.2.5 research baseline'},
    'site-only': {'head': None, 'descriptorSha256': None, 'label': 'site data or captures; no game build evidence'},
    'mixed': {'head': None, 'descriptorSha256': None, 'label': 'several builds compared in one record'},
}
REF_FILES = {'queue-proposals': 'docs/working/FROSTY_RESEARCH_QUEUE.md', 'capture-plan': 'docs/working/BF6_CAPTURE_PRIORITIES.md',
             'open-questions': 'docs/frosty/OPEN_QUESTIONS.md', 'conventions-known-cases': 'docs/working/frosty-worker-conventions.txt'}
QUEUE = 'docs/working/FROSTY_RESEARCH_QUEUE.md'
ARCHIVE = 'docs/archive/FROSTY_QUEUE_CLOSED.md'
GEN_START, GEN_END = '<!-- generated -->', '<!-- /generated -->'
LEAD_ID = re.compile(r'L\d+[A-Z]?')
HEX64 = re.compile(r'[0-9a-f]{64}')
DATE = re.compile(r'\d{4}-\d{2}-\d{2}')
REVISIT = ['Asset content or relevant dependency changes.', 'New evidence identifies a consumer or changes the interpretation.',
           'The research question requires fields or methods outside the inspected scope.']
RECORD_KEYS = {'v', 'kind', 'date', 'build', 'leads', 'assets', 'site', 'siteRows', 'refs', 'supersedes', 'binding', 'run'}
LEAD_KEYS = {'id', 'title', 'status', 'statusNote', 'summary', 'reopenWhen', 'searched'}
ASSET_KEYS = {'path', 'format', 'sha256', 'question', 'result', 'conclusion', 'contents'}
SITE_KEYS = {'pointer', 'value', 'relation'}

SCHEMA_TEXT = f"""Record header v1: a top-level "record" object in every new receipt (draft-receipt.json included).
Receipts committed earlier are byte-frozen; their records live in reference-data/provenance/records-legacy.json.

record:
  v: 1
  kind: {' | '.join(KINDS)}
  date: YYYY-MM-DD                        # must equal the date in the receipt file name
  build: {' | '.join(BUILDS)}
  leads:                                  # required for kind lead/decision
    - id: L17                             # L\\d+ with an optional capital letter (L68C)
      title: short name
      status: {' | '.join(STATUSES)}
      summary: one sentence; becomes the closed-lead row's "Established"
      reopenWhen: one sentence; becomes "Next source step"
      searched: [what was searched]       # required when status is exhausted (fields, value searches, catalog scope, callers)
      statusNote: optional free text shown after the title in the closed-leads table
  assets:                                 # optional; becomes asset-findings.json entries
    - path: internal Frosty path, no .ebx/.xml
      format: {' | '.join(FORMATS)}
      sha256: 64 lowercase hex of the inspected asset in that format
      question: what was asked of this asset
      result: {' | '.join(RESULTS)}
      conclusion: what was found; limited to the stated question
  site:                                   # optional; site pointers this evidence bears on
    - pointer: data/file.json:/path/[key=value]/field     ([key=value]* selects every matching list element)
      value: optional, the site value when the receipt was written
      relation: {' | '.join(RELATIONS)}
  siteRows: optional {{rows: JSON pointer into this receipt, file: i, pointer: i, value: i}}  # audits with hundreds of rows
  refs: optional list of {' | '.join(REF_FILES)}      # the lead id must appear in that document
  supersedes: optional list of receipt file names
  binding: {' | '.join(BINDINGS)}                  # site = pinned by or read by site data/code/tests; research otherwise
  run: optional {{root, orchestrator, workers: [{{lead, model, minutes, tokensM}}]}}
Rules: one record per receipt; a lead's title, status, summary and reopenWhen are the current answer for that lead.
Check a draft with: python scripts/frosty-records.py check-receipt <draft-receipt.json>"""


def sha(b): return hashlib.sha256(b).hexdigest()
def norm(text): return text.replace('\r\n', '\n')
def canon_sha(raw): return sha(raw.replace(b'\r\n', b'\n'))  # the form git stores; independent of checkout line endings
def line_end_hashes(raw):
    lf = raw.replace(b'\r\n', b'\n')
    return {sha(raw), sha(lf), sha(lf.replace(b'\n', b'\r\n'))}
def jdump(obj): return json.dumps(obj, indent=2, ensure_ascii=False) + '\n'
def lead_sort(i): m = re.fullmatch(r'L(\d+)([A-Z]?)', i); return (int(m[1]), m[2]) if m else (10**9, i)
def name_date(name):
    found = DATE.findall(name)
    return found[-1] if found else None
def is_date(s):
    try: datetime.date.fromisoformat(s); return bool(DATE.fullmatch(s))
    except (TypeError, ValueError): return False


class Receipt:
    def __init__(self, name, path, raw):
        self.name, self.path, self.raw, self.err, self.obj = name, path, raw, None, None
        try: self.obj = json.loads(raw.decode('utf-8-sig'))
        except (ValueError, UnicodeDecodeError) as e: self.err = str(e)


class Ctx:
    def __init__(self, a):
        self.site = Path(a.site_root or REPO).resolve()
        self.research = Path(a.research_root or REPO).resolve()
        self.dm = Path(a.datamining_root).resolve() if a.datamining_root else self.research.parent / 'BF6 Datamining'
        self.prov_dirs = [self.research / 'reference-data/provenance']
        if self.site != self.research: self.prov_dirs.append(self.site / 'reference-data/provenance')
        self.frosty = self.research / 'reference-data/frosty'
        self._receipts = self._resolver = None
        self.problems = []  # (severity, category, message)

    def err(self, cat, msg): self.problems.append(('error', cat, msg))
    def warn(self, cat, msg): self.problems.append(('warning', cat, msg))
    def text(self, rel, root=None):
        p = (root or self.research) / rel
        return norm(p.read_text(encoding='utf-8-sig')) if p.exists() else ''

    @property
    def receipts(self):
        if self._receipts is None:
            self._receipts = {}
            for d in self.prov_dirs:
                for p in sorted(d.glob('*.json')):
                    if p.name == SIDECAR: continue
                    if p.name in self._receipts: self.err('receipt', f'{p.name}: exists in more than one provenance folder')
                    self._receipts[p.name] = Receipt(p.name, p, p.read_bytes())
        return self._receipts

    def sidecar(self):
        p = self.prov_dirs[0] / SIDECAR
        if not p.exists(): return {}
        try: data = json.loads(p.read_text(encoding='utf-8-sig'))
        except ValueError as e: self.err('sidecar', f'{SIDECAR} does not parse: {e}'); return {}
        if not isinstance(data, dict): self.err('sidecar', f'{SIDECAR} must be an object keyed by receipt file name'); return {}
        return data

    def pointer_resolver(self):
        """resolve_pointer from frosty-worker.py (single-match behaviour untouched), pointed at --site-root with a file cache."""
        if self._resolver is None:
            fn = runpy.run_path(str(self.research / 'scripts/frosty-worker.py'))['resolve_pointer']
            g, cache, load = fn.__globals__, {}, fn.__globals__['load_json']
            g['ROOT'] = self.site
            def cached(p):
                if str(p) not in cache: cache[str(p)] = load(p)
                return cache[str(p)]
            g['load_json'] = cached
            self._resolver = fn
        return self._resolver

    def resolve_all(self, pointer):
        """Values for a pointer; a `[key=value]*` step expands to every matching list element."""
        fn = self.pointer_resolver()
        file, _, path = pointer.partition(':')
        parts = [p for p in path.split('/') if p]
        for i, part in enumerate(parts):
            m = re.fullmatch(r'\[(\w+)=(.+)\]\*', part)
            if not m: continue
            node = fn(file + ':/' + '/'.join(parts[:i]))
            out = []
            for idx, x in enumerate(node if isinstance(node, list) else []):
                if isinstance(x, dict) and str(x.get(m[1])) == m[2]:
                    out += self.resolve_all(file + ':/' + '/'.join(parts[:i] + [str(idx)] + parts[i + 1:]))
            if not out: raise KeyError(f'{pointer}: no element with {m[1]}={m[2]}')
            return out
        return [fn(pointer)]


# ---------------------------------------------------------------- record validation

def validate_record(rec, name_dt=None):
    """Structural errors for one record object (list of strings)."""
    if not isinstance(rec, dict): return ['record is not an object']
    e = [f'unknown key {k}' for k in sorted(set(rec) - RECORD_KEYS)]
    if rec.get('v') != 1: e.append('v must be 1')
    if rec.get('kind') not in KINDS: e.append(f'kind must be one of {KINDS}')
    d = rec.get('date')
    if not is_date(d): e.append('date must be YYYY-MM-DD')
    elif name_dt and d != name_dt: e.append(f'date {d} differs from the file-name date {name_dt}')
    if rec.get('build') not in BUILDS: e.append(f'build must be one of {list(BUILDS)}')
    if 'binding' in rec and rec['binding'] not in BINDINGS: e.append(f'binding must be one of {BINDINGS}')
    leads = rec.get('leads', [])
    if not isinstance(leads, list): e.append('leads must be a list'); leads = []
    if rec.get('kind') in ('lead', 'decision') and not leads: e.append(f'kind {rec.get("kind")} needs at least one lead')
    seen = set()
    for i, l in enumerate(leads):
        w = f'leads[{i}]'
        if not isinstance(l, dict): e.append(f'{w} is not an object'); continue
        e += [f'{w}: unknown key {k}' for k in sorted(set(l) - LEAD_KEYS)]
        if not (isinstance(l.get('id'), str) and LEAD_ID.fullmatch(l['id'])): e.append(f'{w}: id must look like L17 or L68C')
        elif l['id'] in seen: e.append(f'{w}: duplicate id {l["id"]}')
        else: seen.add(l['id'])
        if l.get('status') not in STATUSES: e.append(f'{w}: status must be one of {STATUSES}')
        for k in ('title', 'summary', 'reopenWhen'):
            if not (isinstance(l.get(k), str) and l[k].strip()): e.append(f'{w}: {k} must be a non-empty string')
        if 'statusNote' in l and not isinstance(l['statusNote'], str): e.append(f'{w}: statusNote must be a string')
        if l.get('status') == 'exhausted' and not (isinstance(l.get('searched'), list) and l['searched'] and all(isinstance(x, str) and x for x in l['searched'])):
            e.append(f'{w}: exhausted needs a non-empty searched list (fields, value searches, catalog scope, callers)')
    assets = rec.get('assets', [])
    if not isinstance(assets, list): e.append('assets must be a list'); assets = []
    for i, a in enumerate(assets):
        w = f'assets[{i}]'
        if not isinstance(a, dict): e.append(f'{w} is not an object'); continue
        e += [f'{w}: unknown key {k}' for k in sorted(set(a) - ASSET_KEYS)]
        if not (isinstance(a.get('path'), str) and a['path'] and not a['path'].lower().endswith(('.ebx', '.xml'))): e.append(f'{w}: path must be an internal Frosty path without .ebx/.xml')
        if a.get('format') not in FORMATS: e.append(f'{w}: format must be one of {FORMATS}')
        if not (isinstance(a.get('sha256'), str) and HEX64.fullmatch(a['sha256'])): e.append(f'{w}: sha256 must be 64 lowercase hex')
        if a.get('result') not in RESULTS: e.append(f'{w}: result must be one of {RESULTS}')
        for k in ('question', 'conclusion'):
            if not (isinstance(a.get(k), str) and a[k].strip()): e.append(f'{w}: {k} must be a non-empty string')
    site = rec.get('site', [])
    if not isinstance(site, list): e.append('site must be a list'); site = []
    for i, s in enumerate(site):
        w = f'site[{i}]'
        if not isinstance(s, dict): e.append(f'{w} is not an object'); continue
        e += [f'{w}: unknown key {k}' for k in sorted(set(s) - SITE_KEYS)]
        if not (isinstance(s.get('pointer'), str) and re.match(r'[^:]+\.(json|js):', s['pointer'])): e.append(f'{w}: pointer must look like data/file.json:/path')
        if s.get('relation') not in RELATIONS: e.append(f'{w}: relation must be one of {RELATIONS}')
    if 'siteRows' in rec:
        sr = rec['siteRows']
        if not (isinstance(sr, dict) and isinstance(sr.get('rows'), str) and all(isinstance(sr.get(k), int) for k in ('file', 'pointer'))):
            e.append('siteRows must be {rows: pointer string, file: int, pointer: int, value: int}')
    if 'refs' in rec and not (isinstance(rec['refs'], list) and set(rec['refs']) <= set(REF_FILES)): e.append(f'refs must be a list drawn from {list(REF_FILES)}')
    if 'supersedes' in rec and not (isinstance(rec['supersedes'], list) and all(isinstance(x, str) for x in rec['supersedes'])): e.append('supersedes must be a list of receipt file names')
    if 'run' in rec and not isinstance(rec['run'], dict): e.append('run must be an object')
    return e


def load_records(ctx):
    """[(name, record, where)] for every receipt; structural problems go to ctx.problems."""
    side, out = ctx.sidecar(), []
    for name, r in ctx.receipts.items():
        if r.err: ctx.err('receipt', f'{name}: does not parse ({r.err})'); continue
        emb = r.obj.get('record') if isinstance(r.obj, dict) else None
        leg = side.get(name)
        if emb is not None and leg is not None: ctx.err('record', f'{name}: has both an embedded record and a {SIDECAR} entry'); continue
        if emb is None and leg is None: ctx.err('record', f'{name}: no record (embed one, or list it in {SIDECAR})'); continue
        if leg is not None:
            if not (isinstance(leg, dict) and isinstance(leg.get('record'), dict) and isinstance(leg.get('sha256'), str)):
                ctx.err('sidecar', f'{name}: entry must be {{"sha256", "record"}}'); continue
            if leg['sha256'] != canon_sha(r.raw): ctx.err('sidecar', f'{name}: file changed since its record was written (committed receipts are superseded, not edited)')
        rec, where = (emb, 'embedded') if leg is None else (leg['record'], 'sidecar')
        errs = validate_record(rec, name_date(name))
        for m in errs: ctx.err('record', f'{name}: {m}')
        if not errs: out.append((name, rec, where))
    for name in sorted(set(side) - set(ctx.receipts)): ctx.err('sidecar', f'{name}: listed in {SIDECAR} but no such receipt')
    return out


# ---------------------------------------------------------------- queue and doc parsing

def section(text, heading):
    """Body of the `heading` section (up to the next heading of the same or a higher level)."""
    m = re.search(r'^(#+) ' + re.escape(heading) + r'\s*$', text, re.M)
    if not m: return ''
    level = len(m[1])
    rest = text[m.end():]
    end = re.search(r'^#{1,%d} ' % level, rest, re.M)
    return rest[:end.start()] if end else rest

def table_rows(body):
    return [[c.strip() for c in l.strip().strip('|').split(' | ')] for l in body.split('\n') if l.startswith('| L')]

def active_leads(ctx):
    return {c[0]: c for c in table_rows(section(ctx.text(QUEUE), 'Active source leads')) if LEAD_ID.fullmatch(c[0])}

def mentions(text, lead_id):
    """The lead id appears in the text, alone or inside a range such as L100-L104."""
    if re.search(r'(?<![A-Za-z0-9])' + re.escape(lead_id) + r'(?![0-9A-Za-z])', text): return True
    n = int(re.sub(r'\D', '', lead_id))
    return any(int(a) <= n <= int(b) for a, b in re.findall(r'L(\d+)[A-Z]?\s*[–—-]\s*L?(\d+)', text))


# ---------------------------------------------------------------- generated files

def index_leads(recs):
    """lead id -> newest entry across records (date, then file name), plus every receipt naming it."""
    per = collections.defaultdict(list)
    for name, rec, _ in recs:
        for l in rec.get('leads', []): per[l['id']].append((rec['date'], name, l, rec))
    out = {}
    for lid in sorted(per, key=lead_sort):
        rows = sorted(per[lid], key=lambda x: (x[0], x[1]))
        date, name, l, rec = rows[-1]
        entry = {'id': lid, 'title': l['title'], 'status': l['status']}
        if l.get('statusNote'): entry['statusNote'] = l['statusNote']
        entry.update({'date': date, 'receipts': [r[1] for r in rows], 'summary': l['summary'], 'reopenWhen': l['reopenWhen'],
                      'refs': sorted({x for r in rows for x in r[3].get('refs', [])})})
        out[lid] = entry
    return out

def closed_table(index, active):
    rows = ['| # | Lead | Established | Next source step |', '|---|---|---|---|']
    for lid, e in index.items():
        if lid in active: continue
        title = e['title'] + (f' - {e["statusNote"]}' if e.get('statusNote') else '')
        rows.append(f'| {lid} | **{title}** | {e["summary"]} | {e["reopenWhen"]} |')
    return '\n'.join(rows)

def render_archive(text, table):
    block = f'{GEN_START}\n<!-- {NOTE} Source: reference-data/frosty/lead-index.json -->\n\n{table}\n{GEN_END}'
    if GEN_START in text and GEN_END in text:
        a, b = text.index(GEN_START), text.index(GEN_END) + len(GEN_END)
        return text[:a] + block + text[b:]
    m = re.search(r'^## Closed leads[ \t]*\n', text, re.M)
    if not m: return None
    nxt = re.search(r'^## ', text[m.end():], re.M)
    end = m.end() + nxt.start() if nxt else len(text)
    return text[:m.end()] + '\n' + block + '\n\n' + text[end:]

def build_findings(ctx, recs):
    base_path = ctx.frosty / 'asset-findings-base.json'
    base = json.loads(base_path.read_text(encoding='utf-8-sig'))
    out = {'schemaVersion': base['schemaVersion'], 'generated': NOTE + ' Base: asset-findings-base.json (frozen); added: record.assets of later receipts.'}
    out.update({k: v for k, v in base.items() if k != 'schemaVersion'})
    out['evidence'], out['assets'] = dict(base['evidence']), {k: {'contents': v['contents'], 'findings': list(v['findings'])} for k, v in base['assets'].items()}
    lower = {k.lower(): k for k in out['assets']}
    stems = {}
    for name, rec, where in sorted(recs, key=lambda x: (x[1]['date'], x[0])):
        if not rec.get('assets'): continue
        stem = name[:-5]; stems[name] = stem
        out['evidence'][stem] = {'path': 'reference-data/provenance/' + name, 'reportSha256': canon_sha(ctx.receipts[name].raw)}
        b = BUILDS[rec['build']]
        reopen = ' '.join(dict.fromkeys(l['reopenWhen'] for l in rec.get('leads', [])))
        for a in rec['assets']:
            key = lower.setdefault(a['path'].lower(), a['path'])
            entry = out['assets'].setdefault(key, {'contents': a.get('contents') or f'Traced by {stem}.', 'findings': []})
            entry['findings'].append({
                'question': a['question'], 'result': a['result'], 'conclusion': a['conclusion'],
                'buildInspected': {'label': b['label'], 'exactBuildVerified': b['head'] is not None,
                                   'basis': f'record.build {rec["build"]}' + (f'; Head {b["head"]}' if b['head'] else '')},
                'evidence': [{'source': stem, 'pointer': '/record' if where == 'embedded' else None}],
                'assetHashesAtInspection': [{'format': a['format'], 'sha256': a['sha256']}],
                'inspectionDate': rec['date'], 'revisitWhen': REVISIT + ([reopen] if reopen else [])})
    ids_by_receipt = {v['path'].rsplit('/', 1)[-1]: k for k, v in out['evidence'].items()}
    for name, rec, _ in recs:  # explicit history links: earlier findings name the record that supersedes them
        if name not in stems: continue
        for old in rec.get('supersedes', []):
            old_id = ids_by_receipt.get(old)
            for asset in out['assets'].values():
                for f in asset['findings']:
                    if old_id and any(e['source'] == old_id for e in f['evidence']):
                        f['supersededBy'] = sorted(set(f.get('supersededBy', []) + [stems[name]]))
    return out

def build_site_evidence(recs):
    ptrs = collections.defaultdict(list)
    for name, rec, _ in recs:
        for s in rec.get('site', []):
            row = {'receipt': name, 'date': rec['date'], 'relation': s['relation']}
            if 'value' in s: row['value'] = s['value']
            ptrs[s['pointer']].append(row)
        sr = rec.get('siteRows')
        if sr: ptrs[f'{name}:{sr["rows"]}'] = [{'receipt': name, 'date': rec['date'], 'relation': 'context', 'siteRows': sr}]
    return {'v': 1, 'generated': NOTE, 'pointers': {p: sorted(ptrs[p], key=lambda r: (r['date'], r['receipt'])) for p in sorted(ptrs)}}

def generate(ctx, recs):
    """relative path (from --research-root) -> generated text."""
    index = index_leads(recs)
    out = {'reference-data/frosty/asset-findings.json': jdump(build_findings(ctx, recs)),
           'reference-data/frosty/lead-index.json': jdump({'v': 1, 'generated': NOTE, 'leads': index}),
           'reference-data/frosty/site-evidence.json': jdump(build_site_evidence(recs))}
    arch = render_archive(ctx.text(ARCHIVE), closed_table(index, active_leads(ctx)))
    if arch is not None: out[ARCHIVE] = arch
    return out


# ---------------------------------------------------------------- site binding, ledger, drift

SITE_FILES = ('index.html', 'ship-surface.json')
def site_layer_files(ctx):
    files = [ctx.site / f for f in SITE_FILES] + [p for d in ('data', 'sim', 'ui', 'schemas', '.github') for p in sorted((ctx.site / d).rglob('*')) if p.is_file()]
    files += [p for p in sorted((ctx.site / 'scripts').glob('*')) if p.suffix in ('.mjs', '.js')]
    return [p for p in files if p.is_file() and p.suffix in ('.json', '.js', '.mjs', '.html', '.yml', '.yaml')]

def derive_binding(ctx):
    """receipt name -> 'site' when a site-layer file pins its sha256 or names it by path, else 'research'."""
    hashes = {}
    for n, r in ctx.receipts.items():
        for h in line_end_hashes(r.raw): hashes[h] = n
    site = set()
    for p in site_layer_files(ctx):
        text = p.read_text(encoding='utf-8', errors='replace')
        site.update(hashes[h] for h in set(HEX64.findall(text)) if h in hashes)
        site.update(n for n in set(re.findall(r'[A-Za-z0-9._-]+\.json', text)) if n in ctx.receipts)
    return {n: ('site' if n in site else 'research') for n in ctx.receipts}

def flatten(o, p=''):
    if isinstance(o, dict) and o:
        for k, v in o.items(): yield from flatten(v, p + '/' + str(k).replace('~', '~0').replace('/', '~1'))
    elif isinstance(o, list) and o:
        for i, v in enumerate(o): yield from flatten(v, p + f'/{i}')
    else: yield p, o

def latest(ctx, pattern):
    return sorted(ctx.prov_dirs[0].glob(pattern), key=lambda p: (re.findall(r'v(\d+)', p.name) or ['0'], p.name))[-1:]

def inventories(ctx):
    """Site-input inventory receipts, newest first: [(path, parsed)]."""
    paths = sorted(ctx.prov_dirs[0].glob('frosty-site-input-inventory-v*.json'), key=lambda p: (int((re.findall(r'-v(\d+)-', p.name) or ['0'])[0]), p.name), reverse=True)
    return [(p, json.loads(p.read_text(encoding='utf-8-sig'))) for p in paths]

def ledger_files(ctx):
    """{site file: (pinned sha256, inventory path, parsed)} from the newest inventory that lists the file as reviewed.
    An inventory marks files it only enumerated (not reviewed) with "reviewed": false; those keep their older baseline."""
    seen = {}
    for p, d in inventories(ctx):
        for f in d.get('files', []):
            if f['path'] not in seen and f.get('reviewed', True): seen[f['path']] = (f['sha256'], p, d)
    return seen

def file_drift(ctx):
    files = ledger_files(ctx)
    out = []
    for rel, (pinned, _, _) in sorted(files.items()):
        p = ctx.site / rel
        if not p.exists(): out.append((rel, 'missing')); continue
        if pinned not in line_end_hashes(p.read_bytes()): out.append((rel, 'changed'))
    return list(files), out

def rebase_external(ctx, path):
    parts = re.split(r'[\\/]', path)
    return ctx.dm.joinpath(*parts[parts.index('BF6 Datamining') + 1:]) if 'BF6 Datamining' in parts else Path(path)

def reviewed_jsonl(ctx):
    rev = latest(ctx, 'frosty-site-input-review-final-v*.json')
    if not rev: return None
    d = json.loads(rev[0].read_text(encoding='utf-8-sig'))
    for p in (d.get('details') or {}).values() if isinstance(d.get('details'), dict) else []:
        if isinstance(p, str) and p.endswith('site-input-reviewed.jsonl'): return rebase_external(ctx, p)
    return None


# ---------------------------------------------------------------- commands

def cmd_schema(a, ctx=None): print(SCHEMA_TEXT)

def run_checks(ctx, external=False):
    recs = load_records(ctx)
    binding = derive_binding(ctx)
    ids = {l['id'] for _, rec, _ in recs for l in rec.get('leads', [])}
    # generated outputs
    if not any(c in ('receipt', 'record', 'sidecar') for _, c, _ in ctx.problems):
        if not (ctx.frosty / 'asset-findings-base.json').exists(): ctx.err('generated', 'reference-data/frosty/asset-findings-base.json is missing')
        else:
            gen = generate(ctx, recs)
            if ARCHIVE not in gen: ctx.err('generated', f'{ARCHIVE}: no "## Closed leads" heading or {GEN_START} markers')
            for rel, text in gen.items():
                p = ctx.research / rel
                if not p.exists() or norm(p.read_text(encoding='utf-8-sig')) != text: ctx.err('generated', f'{rel}: out of date; run build')
    # consistency warnings
    for name, rec, where in recs:
        if 'binding' in rec and rec['binding'] != binding[name]: ctx.warn('binding', f'{name}: record says {rec["binding"]}, the pin/reference scan says {binding[name]}')
        if 'binding' not in rec: ctx.warn('binding', f'{name}: no binding stored (scan says {binding[name]})')
        for old in rec.get('supersedes', []):
            if old not in ctx.receipts: ctx.warn('supersedes', f'{name}: supersedes unknown receipt {old}')
        for ref in rec.get('refs', []):
            doc = ctx.text(REF_FILES[ref]) + (ctx.text(ARCHIVE) if ref == 'queue-proposals' else '')  # applied proposals live in the archive
            if rec.get('leads') and not any(mentions(doc, l['id']) for l in rec['leads']):
                ctx.warn('refs', f'{name}: none of {[l["id"] for l in rec["leads"]]} found in {REF_FILES[ref]}')
        for s in rec.get('site', []):
            try: vals = ctx.resolve_all(s['pointer'])
            except (KeyError, IndexError, ValueError, OSError) as e:
                if s['relation'] != 'changed': ctx.warn('stale-pointer', f'{name}: {e}')
                continue
            if 'value' in s and all(v != s['value'] for v in vals) and s['relation'] != 'changed':
                ctx.warn('value-changed', f'{name}: {s["pointer"]} was {s["value"]!r}, now {vals[0]!r}' if len(vals) == 1 else f'{name}: {s["pointer"]} no longer equals {s["value"]!r}')
        if rec.get('siteRows'): check_site_rows(ctx, name, rec['siteRows'])
    recmap = {n: r for n, r, _ in recs}
    per = collections.defaultdict(list)
    for name, rec, _ in recs:
        for l in rec.get('leads', []): per[l['id']].append((rec['date'], name, l))
    for lid, rows in sorted(per.items(), key=lambda x: lead_sort(x[0])):
        rows.sort(key=lambda x: (x[0], x[1]))
        if len({r[2]['title'] for r in rows}) > 1: ctx.warn('lead-title', f'{lid}: more than one title across {[r[1] for r in rows]}')
        chain = [r[2]['status'] for r in rows]
        if len(set(chain)) > 1 and not any(recmap[r[1]].get('supersedes') for r in rows[1:]):
            ctx.warn('lead-status', f'{lid}: status changes {" -> ".join(chain)} without a superseding record')
    active = active_leads(ctx)
    latest_status = {lid: rows[-1][2]['status'] for lid, rows in per.items()}
    for lid in active:
        if latest_status.get(lid) not in (None, 'needs-capture'): ctx.warn('queue', f'{lid}: in the Active table but its record says {latest_status[lid]}')
    for name in ctx.receipts:
        for tok in set(re.findall(r'(?<![A-Za-z])L(\d+)', name)):
            if f'L{tok}' not in ids and not any(i.startswith(f'L{tok}') for i in ids) and name not in ('records-legacy.json',):
                ctx.warn('lead-record', f'{name}: names L{tok} but no record carries that lead')
    props = section(ctx.text(QUEUE), 'Proposed Analyzer changes') + section(ctx.text(ARCHIVE), 'Applied proposals')
    capture = ctx.text(REF_FILES['capture-plan'])
    for lid, st in sorted(latest_status.items(), key=lambda x: lead_sort(x[0])):
        if st == 'proposal' and not mentions(props, lid): ctx.warn('proposal', f'{lid}: proposal lead is not in the queue proposal table or the applied proposals')
        if st == 'needs-capture' and not mentions(capture, lid): ctx.warn('capture', f'{lid}: needs-capture lead is not in the capture plan')
    files, drift = file_drift(ctx)
    if drift: ctx.warn('ledger-stale', f'{len(drift)} of {len(files)} ledger files differ from the pinned hashes ({", ".join(r for r, _ in drift)}); run ledger-drift')
    if external: external_checks(ctx, recs)
    return recs, drift

def json_pointer(obj, ptr):
    for part in [p for p in ptr.split('/') if p]:
        obj = obj[int(part)] if isinstance(obj, list) else obj[part]
    return obj

def check_site_rows(ctx, name, sr):
    """Audit receipts list site values as rows [file, pointer, value, ...]; warn (once per receipt) about rows that no longer resolve or differ."""
    try: rows = json_pointer(ctx.receipts[name].obj, sr['rows'])
    except (KeyError, IndexError, ValueError, TypeError): ctx.warn('stale-pointer', f'{name}: siteRows.rows {sr["rows"]} not found in the receipt'); return
    gone, moved, first = 0, 0, None
    for row in rows:
        try: vals = ctx.resolve_all(f'{row[sr["file"]]}:{row[sr["pointer"]]}')
        except (KeyError, IndexError, ValueError, OSError): gone += 1; first = first or f'{row[sr["file"]]}:{row[sr["pointer"]]}'; continue
        if 'value' in sr and vals[0] != row[sr['value']]: moved += 1
    if gone: ctx.warn('stale-pointer', f'{name}: {gone} of {len(rows)} siteRows pointers no longer resolve (first: {first})')
    if moved: ctx.warn('value-changed', f'{name}: {moved} of {len(rows)} siteRows values differ from the current site')

def external_checks(ctx, recs):
    if not ctx.dm.exists(): ctx.warn('external', f'{ctx.dm} not found; skipped'); return
    raw_root = ctx.dm / 'builds/1.4.3.0/capture/collection/raw'
    for name, rec, _ in recs:
        for a in rec.get('assets', []):
            f = raw_root / (a['path'] + '.ebx')
            if a['format'] == 'raw-ebx' and f.exists() and sha(f.read_bytes()) != a['sha256']:
                ctx.warn('asset-hash', f'{name}: {a["path"]} raw sha256 differs from the current capture')
    inv = latest(ctx, 'frosty-site-input-inventory-v*.json')
    for x in (json.loads(inv[0].read_text(encoding='utf-8-sig')).get('artifacts', []) if inv else []):
        f = rebase_external(ctx, x['path'])
        if not f.exists(): ctx.warn('external', f'ledger artifact not found: {f}')
        elif sha(f.read_bytes()) != x['sha256']: ctx.warn('external', f'ledger artifact hash differs: {f.name}')
    rj = reviewed_jsonl(ctx)
    if rj is None or not rj.exists(): ctx.warn('external', 'site-input-reviewed.jsonl not found; ledger-row checks skipped')

def print_problems(ctx, show_all=False, limit=8):
    by = collections.defaultdict(list)
    for sev, cat, msg in ctx.problems: by[(sev, cat)].append(msg)
    for (sev, cat), msgs in sorted(by.items(), key=lambda x: (x[0][0] != 'error', x[0][1])):
        for m in (msgs if show_all else msgs[:limit]): print(f'{sev.upper()} [{cat}] {m}')
        if not show_all and len(msgs) > limit: print(f'  ... {len(msgs) - limit} more [{cat}] {sev}s (use --all)')
    return sum(1 for p in ctx.problems if p[0] == 'error'), sum(1 for p in ctx.problems if p[0] == 'warning')

def cmd_check(a, ctx):
    recs, drift = run_checks(ctx, a.external)
    e, w = print_problems(ctx, a.all)
    print(f'{len(ctx.receipts)} receipts, {len(recs)} valid records; {e} errors, {w} warnings')
    sys.exit(1 if e else 0)

def cmd_check_receipt(a, ctx):
    p = Path(a.file)
    try: obj = json.loads(p.read_text(encoding='utf-8-sig'))
    except (OSError, ValueError) as e: raise SystemExit(f'{p}: {e}')
    if not isinstance(obj, dict) or 'record' not in obj: raise SystemExit(f'{p}: no top-level "record" object; run `frosty-records.py schema`')
    errs = validate_record(obj['record'], name_date(p.name))
    if not errs:
        r = obj['record']
        for s in r.get('site', []):
            try: ctx.resolve_all(s['pointer'])
            except (KeyError, IndexError, ValueError, OSError) as e: print(f'WARNING site pointer: {e}')
    for m in errs: print(f'ERROR {m}')
    print(f'{p.name}: {"record ok" if not errs else str(len(errs)) + " errors"}')
    sys.exit(1 if errs else 0)

def cmd_build(a, ctx):
    recs = load_records(ctx)
    bad = [m for s, c, m in ctx.problems if s == 'error' and c in ('receipt', 'record', 'sidecar')]
    if bad:
        for m in bad[:10]: print('ERROR', m)
        raise SystemExit(f'{len(bad)} receipt/record errors; fix them before build')
    gen = generate(ctx, recs)
    if ARCHIVE not in gen: raise SystemExit(f'{ARCHIVE}: no "## Closed leads" heading')
    changed = []
    for rel, text in sorted(gen.items()):
        p = ctx.research / rel
        if p.exists() and norm(p.read_text(encoding='utf-8-sig')) == text: continue
        p.write_text(text, encoding='utf-8', newline='\n'); changed.append(rel)
    print('changed: ' + (', '.join(changed) if changed else 'nothing'))

def cmd_status(a, ctx):
    recs, drift = run_checks(ctx)
    e = sum(1 for p in ctx.problems if p[0] == 'error'); w = sum(1 for p in ctx.problems if p[0] == 'warning')
    index = index_leads(recs)
    active = active_leads(ctx)
    lines = [f'Frosty records: {len(ctx.receipts)} receipts, {len(recs)} records, {len(index)} leads; check {e} errors, {w} warnings']
    if e:
        lines += [f'  ERROR [{c}] {m}'[:150] for s, c, m in ctx.problems if s == 'error'][:5]
    lines.append(f'Live leads (queue Active table, {len(active)}):')
    for lid, c in active.items():
        st = index[lid]['status'] if lid in index else 'no record'
        title = re.sub(r'\*\*|\s+-\s+.*', '', c[1])[:70]
        lines.append(f'  {lid} [{st}] {title}')
    q = ctx.text(QUEUE)
    aw = next((section(q, h) for h in re.findall(r'^### (Awaiting operator[^\n]*)$', q, re.M)), '')
    items = re.findall(r'^- (.*(?:\n  .*)*)', aw, re.M)
    lines.append(f'Awaiting the operator ({len(items)}):')
    for it in items: lines.append('  - ' + re.sub(r'\s+', ' ', re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', it))[:135])
    props = section(q, 'Proposed Analyzer changes')
    pending = [re.sub(r'\*\*|\s+\(L\d.*', '', r[0]).strip()[:60] for r in (l.strip().strip('|').split(' | ') for l in props.split('\n') if l.startswith('| **'))]
    lines.append(f'Proposal rows flagged for the operator ({len(pending)}):')
    for p in pending[:8]: lines.append('  - ' + p)
    if len(pending) > 8: lines.append(f'  ... {len(pending) - 8} more in the queue')
    counts = collections.Counter(e_['status'] for e_ in index.values())
    lines.append('Lead statuses: ' + ', '.join(f'{k} {v}' for k, v in counts.most_common()))
    lines.append('Latest recorded leads:')
    for e_ in sorted(index.values(), key=lambda x: (x['date'], lead_sort(x['id'])), reverse=True)[:6]:
        lines.append(f'  {e_["id"]} {e_["date"]} [{e_["status"]}] {e_["title"][:60]}')
    files, dr = file_drift(ctx)
    lines.append(f'Site-input ledger: {len(dr)} of {len(files)} pinned files changed since the 23 Sep inventory (' + '; '.join(f'{d} {sum(1 for r, _ in dr if r.startswith(d + "/"))}' for d in ('data', 'sim')) + '); ledger-drift lists the leaves')
    stale = sum(1 for s, c, m in ctx.problems if c == 'stale-pointer')
    lines.append(f'Stale site pointers in records: {stale}. Close-out: receipt with a record, topic page, remove the queue row, then build && check.')
    print('\n'.join(lines[:59]))

def artifact_path(ctx, d, suffix):
    return next((rebase_external(ctx, x['path']) for x in d.get('artifacts', []) if x['path'].endswith(suffix)), None)

def review_statuses(ctx):
    """(site file, pointer) -> reviewStatus: the reviewed ledger rows, overlaid by each inventory's delta ledger (oldest first)."""
    status = {}
    rj = reviewed_jsonl(ctx)
    if rj and rj.exists():
        with open(rj, encoding='utf-8') as f:
            for l in f:
                r = json.loads(l); status[(r['siteFile'], r['pointer'])] = r.get('reviewStatus')
    else: print(f'{rj}: reviewed ledger not found; review status omitted')
    for p, d in reversed(inventories(ctx)):
        art = (d.get('delta') or {}).get('artifact')
        f = rebase_external(ctx, art['path']) if art else None
        if f and f.exists():
            with open(f, encoding='utf-8') as fh:
                for l in fh:
                    r = json.loads(l)
                    if r['change'] == 'removed': status.pop((r['siteFile'], r['pointer']), None)
                    else: status[(r['siteFile'], r['pointer'])] = r.get('reviewStatus')
    return status

def code_lines(text):
    """(line number, code) for the nonblank, non-comment lines, as frosty-site-input-inventory.py indexes sim code."""
    out, block = [], False
    for n, original in enumerate(text.splitlines(), 1):
        line = original.strip()
        if block:
            if '*/' in line: block, line = False, line.split('*/', 1)[1].strip()
            else: continue
        if line.startswith('/*'):
            if '*/' in line: line = line.split('*/', 1)[1].strip()
            else: block = True; continue
        if line and not line.startswith('//'): out.append((n, original))
    return out

def sim_diff(ctx, rel, baseline_lines):
    old = [code for f, n, code in baseline_lines if f == rel]
    cur = code_lines((ctx.site / rel).read_text(encoding='utf-8-sig'))
    ranges = []
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, old, [c for _, c in cur], autojunk=False).get_opcodes():
        if tag != 'equal': ranges.append((cur[j1][0] if j2 > j1 else (cur[j1 - 1][0] if j1 else 1), cur[j2 - 1][0] if j2 > j1 else None, i2 - i1, j2 - j1))
    return ranges

def cmd_ledger_drift(a, ctx):
    files, drift = file_drift(ctx)
    seen = ledger_files(ctx)
    print(f'{len(drift)} of {len(files)} ledger files differ from the pinned hashes:')
    for rel, why in drift: print(f'  {rel}: {why} (baseline {seen[rel][1].name})')
    status = review_statuses(ctx)
    out = {'changed': [], 'removed': [], 'new': []}
    by_inv = collections.defaultdict(list)
    for rel in files:
        if rel.startswith('data/'): by_inv[seen[rel][1]].append(rel)
    for inv_path, rels in by_inv.items():
        leaves = artifact_path(ctx, seen[rels[0]][2], 'site-input-leaves.jsonl')
        if leaves is None or not leaves.exists(): print(f'external leaf list not found ({leaves}); skipping leaves for {inv_path.name}'); continue
        old = collections.defaultdict(dict)
        with open(leaves, encoding='utf-8') as f:
            for l in f:
                r = json.loads(l)
                if r['siteFile'] in rels: old[r['siteFile']][r['pointer']] = r['siteValue']
        for rel in sorted(old):
            p = ctx.site / rel
            cur = dict(flatten(json.loads(p.read_text(encoding='utf-8-sig')))) if p.exists() else {}
            for ptr, v in old[rel].items():
                if ptr not in cur: out['removed'].append({'file': rel, 'pointer': ptr, 'was': v, 'review': status.get((rel, ptr))})
                elif cur[ptr] != v: out['changed'].append({'file': rel, 'pointer': ptr, 'was': v, 'now': cur[ptr], 'review': status.get((rel, ptr))})
            for ptr, v in cur.items():
                if ptr not in old[rel]: out['new'].append({'file': rel, 'pointer': ptr, 'now': v})
    print('data leaves: ' + ', '.join(f'{len(v)} {k}' for k, v in out.items()))
    for k, rows in out.items():
        by = collections.Counter(r['file'] for r in rows)
        if by: print(f'  {k}: ' + ', '.join(f'{f} {n}' for f, n in sorted(by.items())))
    sims = [r for r, _ in drift if r.startswith('sim/')]
    if sims:
        baseline = {}
        for rel in sims:
            lines = artifact_path(ctx, seen[rel][2], 'site-simulation-lines.jsonl')
            if lines and lines.exists() and lines not in baseline:
                baseline[lines] = [(r['siteFile'], r['line'], r['code']) for r in map(json.loads, open(lines, encoding='utf-8'))]
            print(f'sim (reported only, not re-reviewed): {rel}: ', end='')
            if lines and lines in baseline:
                rg = sim_diff(ctx, rel, baseline[lines])
                print(f'{len(rg)} changed blocks; ' + ', '.join(f'{s}-{e or s}' for s, e, _, _ in rg[:8]) + (' ...' if len(rg) > 8 else ''))
            else: print('baseline line list not found')
    if a.out:
        Path(a.out).write_text(json.dumps(out, indent=1) + '\n', encoding='utf-8'); print(f'full list: {a.out}')

def cmd_new(a, ctx):
    ids = a.lead or []
    if not ids or not all(LEAD_ID.fullmatch(i) for i in ids): raise SystemExit('give --lead L<number> at least once')
    date = a.date or datetime.date.today().isoformat()
    leads = [{'id': i, 'title': a.title or 'TODO', 'status': a.status, 'summary': a.summary or 'TODO', 'reopenWhen': a.reopen_when or 'TODO'} for i in ids]
    if a.status_note: [l.update(statusNote=a.status_note) for l in leads]
    rec = {'v': 1, 'kind': a.kind, 'date': date, 'build': a.build, 'leads': leads, 'binding': 'research'}
    if a.status == 'exhausted': [l.update(searched=['TODO']) for l in leads]
    body = {'date': date, 'title': a.title or 'TODO', 'record': rec}
    if a.note: body['note'] = a.note
    errs = validate_record(rec, date)
    if errs: raise SystemExit('; '.join(errs))
    out = Path(a.out) if a.out else ctx.prov_dirs[0] / f'frosty-{date}-{a.kind}-{"-".join(ids)}.json'
    if out.exists(): raise SystemExit(f'refusing existing output: {out}')
    out.write_text(jdump(body), encoding='utf-8', newline='\n'); print(out)

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--site-root'); ap.add_argument('--research-root'); ap.add_argument('--datamining-root')
    sub = ap.add_subparsers(dest='cmd', required=True)
    sub.add_parser('schema').set_defaults(f=cmd_schema)
    s = sub.add_parser('check'); s.add_argument('--external', action='store_true'); s.add_argument('--all', action='store_true'); s.set_defaults(f=cmd_check)
    s = sub.add_parser('check-receipt'); s.add_argument('file'); s.set_defaults(f=cmd_check_receipt)
    sub.add_parser('status').set_defaults(f=cmd_status)
    sub.add_parser('build').set_defaults(f=cmd_build)
    s = sub.add_parser('ledger-drift'); s.add_argument('--out'); s.set_defaults(f=cmd_ledger_drift)
    s = sub.add_parser('new'); s.add_argument('--kind', choices=['decision', 'lead'], default='decision'); s.add_argument('--lead', action='append')
    s.add_argument('--status', choices=STATUSES, default='parked'); s.add_argument('--title'); s.add_argument('--summary'); s.add_argument('--reopen-when')
    s.add_argument('--date'); s.add_argument('--build', choices=list(BUILDS), default='site-only'); s.add_argument('--status-note'); s.add_argument('--note'); s.add_argument('--out'); s.set_defaults(f=cmd_new)
    sys.stdout.reconfigure(encoding='utf-8')
    a = ap.parse_args(); a.f(a, Ctx(a))

if __name__ == '__main__':
    main()
